# Generated by Django 2.2 on 2020-09-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
